######################################################################
# Automatically generated by qmake (3.0) Tue Aug 8 14:19:53 2017
######################################################################

TEMPLATE = app
TARGET = Leeds
INCLUDEPATH += . /opt/local/include

QT += widgets opengl gui
LIBS += -lglut -lGLU

# Input
HEADERS += LeedsWidget.h LeedsWindow.h
SOURCES += Main.cpp \
           LeedsWidget.cpp \
           LeedsWindow.cpp \
           Image.cpp
